tasks:
  - name: Dev Server
    init: |
      npm install
      npm run build
    command: npm run dev
github:
  prebuilds:
    main: true
# Ports to expose on workspace startup
ports:
  - port: 3000
    onOpen: notify
  - port: 3021
    onOpen: ignore
  - port: 9630
    onOpen: ignore
vscode:
  extensions:
    - betterthantomorrow.calva