tasks:
  - name: Dev Server
    env:
      SQUARITY_M2_LOCAL_REPO: /workspace/.m2/repository
    init: |
      npm install
      npm run classpath
    command: npm run dev
github:
  prebuilds:
    main: true
# Ports to expose on workspace startup
ports:
  - port: 3000
    onOpen: notify
  - port: 3021
    onOpen: ignore
  - port: 9630
    onOpen: ignore
vscode:
  extensions:
    - betterthantomorrow.calva
    - bradlc.vscode-tailwindcss