name: Azure CI/CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - ".gitignore"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SERVICE_PRINCIPLE }}
      - name: 'Check if infrastructure code has changed'
        id: infrastructure-code
        uses: technote-space/get-diff-action@v4.0.1
        with:
          PATTERNS: |
            azuredeploy.bicep
            azuredeploy.parameters.json
      - name: 'Deploy infrastructure'
        id: infra
        if: steps.infrastructure-code.outputs.diff
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./azuredeploy.bicep
          parameters: ./azuredeploy.parameters.json
          failOnStdErr: false
          deploymentMode: Complete
      # Building outside the container is necessary because java is required
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Deps
        run: npm ci
      - name: Build
        run: npm run release # <- ClojureScript compilation with shadow-cljs, which is what requires java
      - name: Zip
        run: '(cd public && zip -r ../app.zip .)'
      - name: Deploy Azure Web App
        id: deploywebapp
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: az webapp deploy --resource-group ${{ secrets.AZURE_RG }} --name squarity --src-path app.zip
